FROM maven:3.8.3-openjdk-17 AS build
RUN mkdir /project
COPY . /project
WORKDIR /project
RUN mvn clean package -DskipTests


FROM eclipse-temurin:17-jre-alpine AS deployable
RUN apk add dumb-init
RUN mkdir /app
RUN addgroup --system javauser && adduser -S -s /bin/false -G javauser javauser
COPY --from=build /project/orchestration/target/authable-* /app/authable.jar

WORKDIR /app
RUN chown -R javauser:javauser /app
USER javauser
CMD "dumb-init" "java" "-jar" "authable.jar"

# RUN apt-get update && apt-get install bash
# RUN mkdir -p /usr/app/
# ENV PROJECT_HOME /usr/app/
# COPY orchestration/target/authable-*.jar $PROJECT_HOME/authable.jar
# WORKDIR $PROJECT_HOME
# EXPOSE 9501
# CMD ["java", "-jar", "./authable.jar"]