DROP DATABASE IF EXISTS `AUTHABLE`;

CREATE DATABASE IF NOT EXISTS `AUTHABLE`;

USE `AUTHABLE`;

DROP TABLE IF EXISTS `SYSTEM_MASTER`;
CREATE TABLE IF NOT EXISTS `SYSTEM_MASTER`
(
    `SYSTEM_ID` char
(
    5
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `SYSTEM_NAME` varchar
(
    50
) NOT NULL DEFAULT '',
    `SYSTEM_DESCRIPTION` varchar
(
    100
) NOT NULL,
    `STATUS` char
(
    1
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `MODIFICATION_ID` varchar
(
    20
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `MODIFICATION_DATE_TIME` datetime NOT NULL,
    `CREATION_ID` varchar
(
    20
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `CREATION_DATE_TIME` datetime NOT NULL,
    PRIMARY KEY
(
    `SYSTEM_ID`
)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `SYSTEM_MESSAGES`;
CREATE TABLE IF NOT EXISTS `SYSTEM_MESSAGES`
(
    `MESSAGE_CODE` char
(
    4
) NOT NULL,
    `MESSAGE_VALUE` varchar
(
    250
) NOT NULL,
    `MESSAGE_DESCRIPTION` varchar
(
    250
) NOT NULL DEFAULT '',
    `STATUS` char
(
    1
) NOT NULL DEFAULT '',
    `MODIFICATION_ID` varchar
(
    20
) NOT NULL,
    `MODIFICATION_DATE_TIME` datetime NOT NULL,
    `CREATION_ID` varchar
(
    20
) NOT NULL,
    `CREATION_DATE_TIME` datetime NOT NULL,
    PRIMARY KEY
(
    `MESSAGE_CODE`
)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `SYSTEM_USER_MASTER`;
CREATE TABLE IF NOT EXISTS `SYSTEM_USER_MASTER`
(
    `ACCESS_ID` char
(
    36
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `SYSTEM_ID` char
(
    5
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `USER_NAME` varchar
(
    50
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `USER_SECRET` varchar
(
    512
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `USER_FULL_NAME` varchar
(
    100
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    `USER_IP_RANGE` varchar
(
    500
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `NO_OF_ATTEMPTS` smallint NOT NULL DEFAULT '0',
    `LAST_LOGIN_DATE_TIME` datetime DEFAULT NULL,
    `INVALID_ATTEMPT_DATE_TIME` datetime DEFAULT NULL,
    `LOCKED_DATE_TIME` datetime DEFAULT NULL,
    `STATUS` char
(
    1
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `MODIFICATION_ID` varchar
(
    20
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `MODIFICATION_DATE_TIME` datetime NOT NULL,
    `CREATION_ID` varchar
(
    20
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `CREATION_DATE_TIME` datetime NOT NULL,
    PRIMARY KEY
(
    `ACCESS_ID`
) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `TOTP_USER_MASTER`;
CREATE TABLE IF NOT EXISTS `TOTP_USER_MASTER`
(
    `TOTP_USER_ID` char
(
    50
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    `SYSTEM_ID` char
(
    5
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `TOTP_USER_SECRET` varchar
(
    250
) NOT NULL DEFAULT '',
    `NO_OF_ATTEMPTS` smallint NOT NULL,
    `LAST_LOGIN_DATE_TIME` datetime DEFAULT NULL,
    `INVALID_ATTEMPT_DATE_TIME` datetime DEFAULT NULL,
    `LOCKED_DATE_TIME` datetime DEFAULT NULL,
    `ACCESS_TYPE` char
(
    1
) NOT NULL DEFAULT '',
    `STATUS` char
(
    1
) NOT NULL,
    `MODIFICATION_ID` varchar
(
    50
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `MODIFICATION_DATE_TIME` datetime NOT NULL,
    `CREATION_ID` varchar
(
    50
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `CREATION_DATE_TIME` datetime NOT NULL,
    PRIMARY KEY
(
    `TOTP_USER_ID`
) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_0900_ai_ci;

INSERT INTO AUTHABLE.SYSTEM_MASTER (SYSTEM_ID,SYSTEM_NAME,SYSTEM_DESCRIPTION,STATUS,MODIFICATION_ID,
MODIFICATION_DATE_TIME,CREATION_ID,CREATION_DATE_TIME)
VALUES
('MAIN-','MAIN','ROOT SYSTEM NAME','A','DEFAULT',NOW(),'DEFAULT',NOW());

INSERT INTO AUTHABLE.SYSTEM_USER_MASTER (ACCESS_ID,SYSTEM_ID,USER_NAME,USER_SECRET,USER_FULL_NAME,
USER_IP_RANGE,NO_OF_ATTEMPTS,LAST_LOGIN_DATE_TIME,INVALID_ATTEMPT_DATE_TIME,
LOCKED_DATE_TIME,STATUS,MODIFICATION_ID,MODIFICATION_DATE_TIME,CREATION_ID,CREATION_DATE_TIME)
VALUES
('53cb6d96-aae3-47ea-accc-15039da60d13','MAIN-','ROOT',
 '696ad9cc8707d16da7c03e157026240ddef4d3287e588070a86128811cc1bac9988aa47370a84104780ed27189912cd76531e4a732f2e700e85de841be1f21a1',
 'ROOT','',0,NULL,NULL,NULL,'A','DEFAULT',NOW(),'DEFAULT',NOW());


INSERT INTO AUTHABLE.SYSTEM_MASTER (SYSTEM_ID,SYSTEM_NAME,SYSTEM_DESCRIPTION,STATUS,MODIFICATION_ID,
MODIFICATION_DATE_TIME,CREATION_ID,CREATION_DATE_TIME)
VALUES
('DEMO-','DEMO','DEMO FOR EXAMPLE SYSTEM','A','DEFAULT',NOW(),'DEFAULT',NOW());

INSERT INTO AUTHABLE.SYSTEM_USER_MASTER (ACCESS_ID,SYSTEM_ID,USER_NAME,USER_SECRET,USER_FULL_NAME,
USER_IP_RANGE,NO_OF_ATTEMPTS,LAST_LOGIN_DATE_TIME,INVALID_ATTEMPT_DATE_TIME,
LOCKED_DATE_TIME,STATUS,MODIFICATION_ID,MODIFICATION_DATE_TIME,CREATION_ID,CREATION_DATE_TIME)
VALUES
('4216f1d5-cbe3-4dfb-92f7-3415fc757030','DEMO-','EXAMPLE',
 'b592b18637e6132f7d14f5140cb6b1a0fed7ccbb7ee17367ee3fae49b0eedd9a736e62c9a2932c04bc2538bafcb484a3dcb7b8d183e49b25c7cf16ebc0324912',
 'EXAMPLE','',0,NULL,NULL,NULL,'A','EXAMPLE',NOW(),'EXAMPLE',NOW());

