DROP DATABASE IF EXISTS `AUTHABLE`;

CREATE DATABASE IF NOT EXISTS `AUTHABLE`;

USE `AUTHABLE`;

DROP TABLE IF EXISTS `SYSTEM_MASTER`;
CREATE TABLE IF NOT EXISTS `SYSTEM_MASTER`
(
    `SYSTEM_ID` char
(
    5
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `SYSTEM_NAME` varchar
(
    50
) NOT NULL DEFAULT '',
    `SYSTEM_DESCRIPTION` varchar
(
    100
) NOT NULL,
    `STATUS` char
(
    1
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `MODIFICATION_ID` varchar
(
    20
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `MODIFICATION_DATE_TIME` datetime NOT NULL,
    `CREATION_ID` varchar
(
    20
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `CREATION_DATE_TIME` datetime NOT NULL,
    PRIMARY KEY
(
    `SYSTEM_ID`
)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `SYSTEM_MESSAGES`;
CREATE TABLE IF NOT EXISTS `SYSTEM_MESSAGES`
(
    `MESSAGE_CODE` char
(
    4
) NOT NULL,
    `MESSAGE_VALUE` varchar
(
    250
) NOT NULL,
    `MESSAGE_DESCRIPTION` varchar
(
    250
) NOT NULL DEFAULT '',
    `STATUS` char
(
    1
) NOT NULL DEFAULT '',
    `MODIFICATION_ID` varchar
(
    20
) NOT NULL,
    `MODIFICATION_DATE_TIME` datetime NOT NULL,
    `CREATION_ID` varchar
(
    20
) NOT NULL,
    `CREATION_DATE_TIME` datetime NOT NULL,
    PRIMARY KEY
(
    `MESSAGE_CODE`
)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `SYSTEM_USER_MASTER`;
CREATE TABLE IF NOT EXISTS `SYSTEM_USER_MASTER`
(
    `ACCESS_ID` char
(
    36
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `SYSTEM_ID` char
(
    5
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `USER_NAME` varchar
(
    50
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `USER_SECRET` varchar
(
    512
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `USER_FULL_NAME` varchar
(
    100
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    `USER_IP_RANGE` varchar
(
    500
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `NO_OF_ATTEMPTS` smallint NOT NULL DEFAULT '0',
    `LAST_LOGIN_DATE_TIME` datetime DEFAULT NULL,
    `INVALID_ATTEMPT_DATE_TIME` datetime DEFAULT NULL,
    `LOCKED_DATE_TIME` datetime DEFAULT NULL,
    `STATUS` char
(
    1
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `MODIFICATION_ID` varchar
(
    20
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `MODIFICATION_DATE_TIME` datetime NOT NULL,
    `CREATION_ID` varchar
(
    20
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `CREATION_DATE_TIME` datetime NOT NULL,
    PRIMARY KEY
(
    `ACCESS_ID`
) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `TOTP_USER_MASTER`;
CREATE TABLE IF NOT EXISTS `TOTP_USER_MASTER`
(
    `TOTP_USER_ID` char
(
    50
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    `SYSTEM_ID` char
(
    5
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `TOTP_USER_SECRET` varchar
(
    250
) NOT NULL DEFAULT '',
    `NO_OF_ATTEMPTS` smallint NOT NULL,
    `LAST_LOGIN_DATE_TIME` datetime DEFAULT NULL,
    `INVALID_ATTEMPT_DATE_TIME` datetime DEFAULT NULL,
    `LOCKED_DATE_TIME` datetime DEFAULT NULL,
    `ACCESS_TYPE` char
(
    1
) NOT NULL DEFAULT '',
    `STATUS` char
(
    1
) NOT NULL,
    `MODIFICATION_ID` varchar
(
    50
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `MODIFICATION_DATE_TIME` datetime NOT NULL,
    `CREATION_ID` varchar
(
    50
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `CREATION_DATE_TIME` datetime NOT NULL,
    PRIMARY KEY
(
    `TOTP_USER_ID`
) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_0900_ai_ci;

INSERT INTO AUTHABLE.SYSTEM_MASTER (SYSTEM_ID,SYSTEM_NAME,SYSTEM_DESCRIPTION,STATUS,MODIFICATION_ID,
MODIFICATION_DATE_TIME,CREATION_ID,CREATION_DATE_TIME)
VALUES
('MAIN','MAIN','ROOT SYSTEM NAME','A','DEFAULT',NOW(),'DEFAULT',NOW());

INSERT INTO AUTHABLE.SYSTEM_USER_MASTER (ACCESS_ID,SYSTEM_ID,USER_NAME,USER_SECRET,USER_FULL_NAME,
USER_IP_RANGE,NO_OF_ATTEMPTS,LAST_LOGIN_DATE_TIME,INVALID_ATTEMPT_DATE_TIME,
LOCKED_DATE_TIME,STATUS,MODIFICATION_ID,MODIFICATION_DATE_TIME,CREATION_ID,CREATION_DATE_TIME)
VALUES
('10b750fe-703f-4c98-ac92-1ff7b6270c09','MAIN','root',
'a702ca321d273103604f12a8cc40de3b2acf542eb7ba54863eb0d074d31d6a74a36b406cd9320277d3334ea46f91b11fd827808be7b18b9ec1bf76725d66b8db',
'Root User','',0,NULL,NULL,NULL,'A','DEFAULT',NOW(),DEFAULT,NOW());


INSERT INTO AUTHABLE.SYSTEM_MASTER (SYSTEM_ID,SYSTEM_NAME,SYSTEM_DESCRIPTION,STATUS,MODIFICATION_ID,
                                    MODIFICATION_DATE_TIME,CREATION_ID,CREATION_DATE_TIME)
VALUES
    ('DEMO','DEMO','DEMO FOR EXAMPLE SYSTEM','A','DEFAULT',NOW(),'DEFAULT',NOW());

INSERT INTO AUTHABLE.SYSTEM_USER_MASTER (ACCESS_ID,SYSTEM_ID,USER_NAME,USER_SECRET,USER_FULL_NAME,
                                         USER_IP_RANGE,NO_OF_ATTEMPTS,LAST_LOGIN_DATE_TIME,INVALID_ATTEMPT_DATE_TIME,
                                         LOCKED_DATE_TIME,STATUS,MODIFICATION_ID,MODIFICATION_DATE_TIME,CREATION_ID,CREATION_DATE_TIME)
VALUES
    ('2c6ec109-fb7d-4c08-aa5a-97a1feeb1eee','DEMO','EXAMPLE',
     'a702ca321d273103604f12a8cc40de3b2acf542eb7ba54863eb0d074d31d6a74a36b406cd9320277d3334ea46f91b11fd827808be7b18b9ec1bf76725d66b8db',
     'Example Demo User','',0,NULL,NULL,NULL,'A','DEFAULT',NOW(),DEFAULT,NOW());
