USE
`authable`;

DROP TABLE IF EXISTS `SYSTEM_MASTER`;
CREATE TABLE IF NOT EXISTS `SYSTEM_MASTER`
(
    `SYSTEM_ID` char
(
    5
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `SYSTEM_NAME` varchar
(
    50
) NOT NULL DEFAULT '',
    `SYSTEM_DESCRIPTION` varchar
(
    100
) NOT NULL,
    `STATUS` char
(
    1
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `MODIFICATION_ID` varchar
(
    20
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `MODIFICATION_DATE_TIME` datetime NOT NULL,
    `CREATION_ID` varchar
(
    20
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `CREATION_DATE_TIME` datetime NOT NULL,
    PRIMARY KEY
(
    `SYSTEM_ID`
)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `SYSTEM_MESSAGES`;
CREATE TABLE IF NOT EXISTS `SYSTEM_MESSAGES`
(
    `MESSAGE_CODE` char
(
    4
) NOT NULL,
    `MESSAGE_VALUE` varchar
(
    250
) NOT NULL,
    `MESSAGE_DESCRIPTION` varchar
(
    250
) NOT NULL DEFAULT '',
    `STATUS` char
(
    1
) NOT NULL DEFAULT '',
    `MODIFICATION_ID` varchar
(
    20
) NOT NULL,
    `MODIFICATION_DATE_TIME` datetime NOT NULL,
    `CREATION_ID` varchar
(
    20
) NOT NULL,
    `CREATION_DATE_TIME` datetime NOT NULL,
    PRIMARY KEY
(
    `MESSAGE_CODE`
)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `SYSTEM_USER_MASTER`;
CREATE TABLE IF NOT EXISTS `SYSTEM_USER_MASTER`
(
    `ACCESS_ID` char
(
    36
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `SYSTEM_ID` char
(
    5
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `USER_NAME` varchar
(
    50
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `USER_SECRET` varchar
(
    512
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `USER_FULL_NAME` varchar
(
    100
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    `USER_IP_RANGE` varchar
(
    500
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `NO_OF_ATTEMPTS` smallint NOT NULL DEFAULT '0',
    `LAST_LOGIN_DATE_TIME` datetime DEFAULT NULL,
    `INVALID_ATTEMPT_DATE_TIME` datetime DEFAULT NULL,
    `LOCKED_DATE_TIME` datetime DEFAULT NULL,
    `STATUS` char
(
    1
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `MODIFICATION_ID` varchar
(
    20
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `MODIFICATION_DATE_TIME` datetime NOT NULL,
    `CREATION_ID` varchar
(
    20
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `CREATION_DATE_TIME` datetime NOT NULL,
    PRIMARY KEY
(
    `ACCESS_ID`
) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `TOTP_USER_MASTER`;
CREATE TABLE IF NOT EXISTS `TOTP_USER_MASTER`
(
    `TOTP_USER_ID` char
(
    50
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    `SYSTEM_ID` char
(
    5
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `TOTP_USER_SECRET` varchar
(
    250
) NOT NULL DEFAULT '',
    `NO_OF_ATTEMPTS` smallint NOT NULL,
    `LAST_LOGIN_DATE_TIME` datetime DEFAULT NULL,
    `INVALID_ATTEMPT_DATE_TIME` datetime DEFAULT NULL,
    `LOCKED_DATE_TIME` datetime DEFAULT NULL,
    `ACCESS_TYPE` char
(
    1
) NOT NULL DEFAULT '',
    `STATUS` char
(
    1
) NOT NULL,
    `MODIFICATION_ID` varchar
(
    50
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `MODIFICATION_DATE_TIME` datetime NOT NULL,
    `CREATION_ID` varchar
(
    50
) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
    `CREATION_DATE_TIME` datetime NOT NULL,
    PRIMARY KEY
(
    `TOTP_USER_ID`
) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE =utf8mb4_0900_ai_ci;

